### ISSUE TITLE
enumについて調べる

### ISSUE THREAD

**Issue by ms2sato** [solve0919/orders#6]
今後Railsでコードを書いていく中で、 enum という機能によく出会います。以下の点について調査してこのIssue内でまとめてみましょう。

- そもそもenumとは何か
- enumを使うとでできるようになること
- enumを使う際の日本語化（i18n）について

**Comment by solve0919** [comment]
>そもそもenumとは何か
enumとは数字に名前(意味)を付けること。

>enumを使うとでできるようになること
ex.未完成:0 作業中:1 完了:2 ,発送前:0 発送中:1 発送完了:2 等
数字だけでは分かりにくい作業状況や発送状況等
を別の作業担当者が見てもすぐに理解しやすくなる。

>enumを使う際の日本語化（i18n）について
gem 'enum_help' を indtall
利用者が日本語で分かる様(日本語で出力出来るように)に導入する。
"_i18n"をメソッドのあとに記載する。
ex.app/config/locals/ja.yml
ja:
  enums:
    battle:
      status:
        attack: 攻撃
        spells: 魔法
        defend: 防御
        item: アイテム
        abilities: 特技

**Comment by ms2sato** [comment]
@solve0919 書いてくれている内容はほぼOKですね！すでにサービスに組み込み始めている様子ですが、日本語化については i18nについて少し調べていれてみてください。
